### ISSUE TITLE
Error with timezone

### ISSUE THREAD

**Issue by Provson** [flexmonster/ng-flexmonster#1]
Hi,

I create a jsfiddle : [here](https://jsfiddle.net/Provson/a1p8svhq/16/)
I use this date  : 2016-02-06T00:00:00+01:00 (GMT+1)
When I add this fields date.Day, date.Month and date.Year, the date displayed is not 2016-02-06 but 2016-02-05.
If my column type is set to 'date string', the date displayed is correct.

Can you help me ?

**Comment by flexmonster** [comment]
Hello Provson,
Thank you for writing. The "datePattern" is applicable only for the "date string" data type. When you use "date" data type the component shows the UTC date. It means that if the input data is 2016-02-06T00:00:00+01:00 (GMT+1) the UTC output is 2016-02-05T23:00:00+00:00 (UTC). In such case, we recommend defining the input data the following way: 2016-02-06T00:00:00Z (UTC). That should solve the case.
Also, could you please specify whether your company is the client of Flexmonster? We need this information for our records.
Let us know in case of any other question.
Regards,
Flexmonster Team

**Comment by Provson** [comment]
Hi,
We are a client of your company (Hitech Software, France).
I understand your answer but my server give me dates with timezone. If the server ommit timezone, all dates in the projets will be wrong.

**Comment by flexmonster** [comment]
Hello Provson,
Thank you for your feedback. 
Our dev team would need to spend some time on the investigation of this case.
We will keep you updated.
Regards,
Dmytro

**Comment by flexmonster** [comment]
Hello Provson,
Thank you for giving us some time.
We are going to add a new property which should allow applying the timezone for the "date" data type.
Such an approach should solve the case.
The necessary update is going to be added to the minor release with ETA Jan14.
We will notify you about the update.
Regards,
Dmytro

**Comment by Provson** [comment]
Hi, any update ?
The flexmonster package was updated but the ng-flexmonster wasn't, so I don't have the new option.

Regards,
Provson

**Comment by flexmonster** [comment]
Hello Provson,
Thank you for writing to us. We have just updated the ng-flexmonster module. You are welcome to try it.
Please find the example of using the new property for date timezones [here](https://jsfiddle.net/flexmonster/8p1s7cd4/3/).
Let us know if everything works fine for you.
Regards,
Flexmonster Team.

**Comment by Provson** [comment]
Hi,
It works.
To complete your example, if someone wants to use javascript date, you need to use this code:
`yourDate.getTimezoneOffset() / 60 * -1`
