### ISSUE TITLE
Typings do not have `fieldListPosition` for Options object

### ISSUE THREAD

**Issue by ezk84** [flexmonster/ng-flexmonster#3]
The `flexmonster.d.ts` file does not list `fieldListPosition` as a possible field in the Options object.

This would need to be added to the list:

```ts
interface Options {
    ...
    fieldListPosition?: "right" | undefined;
}
```

**Comment by VeraDidenko** [comment]
Hello, 

 

Thank you for noticing. 

 

We are happy to inform you that our team has added the `fieldListPosition` property to the TypeScript definitions.

You are welcome to update the component.

 

Please let us know if everything works fine for you.

 

Kind regards, 
Vera
