### ISSUE TITLE
Changing report via component's `report` input doesn't work

### ISSUE THREAD

**Issue by ezk84** [flexmonster/ng-flexmonster#5]
I cannot change the active report of the PivotComponent by changing it's `[report]` value, as illustrated by the following code.

I would expect that after pressing the "Change report" button I would have a new report load into the pivot table.

app.component.ts
```ts
@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.scss"],
})
export class AppComponent {
    report: Flexmonster.Report = report1;

    changeReport() {
        this.report = report2;
    }
}

const report1: Flexmonster.Report = {
    "dataSource": {
        "dataSourceType": "csv",
        "filename": "https://cdn.flexmonster.com/data/data.csv"
    },
    "slice": {
        "rows": [{
            "uniqueName": "Country"
        }, {
            "uniqueName": "[Measures]"
        }],
        "columns": [{
            "uniqueName": "Category"
        }],
        "measures": [{
                "uniqueName": "Price",
                "aggregation": "sum"
            },
            {
                "uniqueName": "Quantity",
                "aggregation": "average"
            }
        ]
    }
};

const report2: Flexmonster.Report = {
    "dataSource": {
        "dataSourceType": "csv",
        "filename": "https://cdn.flexmonster.com/data/data.csv"
    },
    "slice": {
        "rows": [{
            "uniqueName": "Country"
        }, {
            "uniqueName": "[Measures]"
        }],
        "columns": [{
            "uniqueName": "Category"
        }, {
            "uniqueName": "Destination"
        }],
        "measures": [{
                "uniqueName": "Price",
                "aggregation": "sum"
            },
            {
                "uniqueName": "Quantity",
                "aggregation": "average"
            }
        ],
        "expands": {
            "expandAll": true,
        },
    }
};
```

And app.component.html

```html
<button (click)="changeReport()">Change report</button>
<fm-pivot
  [licenseKey]="'Z7GX-XBJ315-6D0671-056R4Q'"
  [report]="report"
  [toolbar]="true"
  >
</fm-pivot>

```

**Comment by pechurkam** [comment]
Hello!

Thank you for your question.

To change the report, our team kindly suggests using [the setReport() API call](https://www.flexmonster.com/api/setreport/?hilite=%22setReport%22). 
Please have a look at the `onReportComplete()` function in [the Angular example](https://github.com/flexmonster/pivot-angular/blob/master/src/app/home/home.component.ts).

We hope it helps. Do not hesitate to contact us if any further questions arise.

Kind regards,
Milena

**Comment by chriszrc** [comment]
report is setup correctly as an @Input, but it should be placed on a setter method, and on changes the report should be passed to the flexmonster instance. This is highly "un-angular" to not support async inputs-

https://angular.io/guide/component-interaction#intercept-input-property-changes-with-a-setter

**Comment by tsshn** [comment]
Hello,

We want to confirm that the current implementation only allows interacting with a component by using dedicated API calls.
Still, the Flexmonster Angular module is opened to edit. You are welcome to adjust the behavior according to your specific needs.

Regards,
Illia
